### ISSUE TITLE
[Email protected] nel profilo utente

### ISSUE THREAD

**Issue by sirmmo** [Mensa-Italia/mensa_italia_app#2]

**Comment by Sipioteo** [comment]
Non bug, è Area 32 che per decriptare la mail richiede l'esecuzione di un codice Nativo Javascript. Non si può risolvere.

**Comment by Alex45463** [comment]
Salve ho visto l'issue e in realtà con un po' di debug ho risolto.
Ho fatto reverse engineering e tradotto il codice js in dart.
Ditemi però se siete ancora interessati alla feature.

**Comment by Sipioteo** [comment]
> Salve ho visto l'issue e in realtà con un po' di debug ho risolto. Ho fatto reverse engineering e tradotto il codice js in dart. Ditemi però se siete ancora interessati alla feature.

Crea un pull con la feature nuova, al prossimo aggiornamento così sarà disponibile per tutti.
