### ISSUE TITLE
Migliorie Pagina convenzioni

### ISSUE THREAD

**Issue by ilMagnifico** [Mensa-Italia/mensa_italia_app#26]
Nella pagina convenzioni mancherebbe (importante) il referente di quella convenzione, e non per tutte le convenzioni è presente, quindi suggerirei di aggiungere all’interno della scheda della convenzione il socio referente. Sia per avere un’idea di chi contattare nel caso ci fossero aggiornamenti su quelle particolari convenzione sia per eventuali problemi su quella convenzione, insomma un punto di riferimento.

Seconda accorgimento si potrebbe implementare una view come per gli eventi geolocalizzare in base a dove sono presenti queste convenzioni

Terza accorgimento, predisporre anche qui dei filtri, in modo che si possano vedere, selezionando un particolare filtro tutte le convenzioni di quella particolare categoria ad esempio informatica, palestra ecc

**Comment by Sipioteo** [comment]
> Nella pagina convenzioni mancherebbe (importante) il referente di quella convenzione, e non per tutte le convenzioni è presente, quindi suggerirei di aggiungere all’interno della scheda della convenzione il socio referente. Sia per avere un’idea di chi contattare nel caso ci fossero aggiornamenti su quelle particolari convenzione sia per eventuali problemi su quella convenzione, insomma un punto di riferimento.
> 
> Seconda accorgimento si potrebbe implementare una view come per gli eventi geolocalizzare in base a dove sono presenti queste convenzioni
> 
> Terza accorgimento, predisporre anche qui dei filtri, in modo che si possano vedere, selezionando un particolare filtro tutte le convenzioni di quella particolare categoria ad esempio informatica, palestra ecc

Le convenzioni hanno una scheda aggiuntiva con i dati del socio referente. Questa scheda è visibile solo da chi gestisce e modera le convenzioni (per motivi di privacy) e può essere usata da questa persona per tracciare i contatti e ricontattare in caso di problemi.

**Comment by ilMagnifico** [comment]
Altrimenti se proprio non si vuole aggiungere un field a riguardo, che sia **sempre** specificato chi sia il referente, perché in alcune convenzioni non è indicato, ne deducibile.
